import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import MainPage from './MainPage'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href='/favicon.ico' />
      </Head>
      <main className='p-5 overflow-y-hidden'>
        <h1 className='font-bold text-2xl font-inter text-slate-600 text-center pb-3'>Beautwitter</h1>
        <MainPage />
      </main>
    </div>
  )
}
